# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/build-challenge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/editor-basics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/editor-script-box"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/howto-gallery"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/script-box"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ts-starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ts-starter-complete-cotta"
    schedule:
      interval: "weekly"
